apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: 446510550067.dkr.ecr.us-east-1.amazonaws.com/chatbot-repo/server:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  selector:
    app: chatbot
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000