apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
spec:
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: chatbot:latest
        ports:
        - containerPort: 8000
      - name: streamlit
        image: streamlit:latest
        ports:
        - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: chatbot
spec:
  selector:
    app: chatbot
  ports:
  - protocol: TCP
    port: 8000
    # targetPort: 8000